#Internet apps
IMAGE_INSTALL += "\
    firefox \
    qbittorrent \
    kvirc \
    "
#Multimedia apps
IMAGE_INSTALL += "\
    gstreamer1.0-plugins-base \
    gst-plugins-good \
    gst-plugins-bad \
    gst-plugins-ugly \
    mpv \
    audacious \
    audacious-plugins \
    "

#Productivity
IMAGE_INSTALL +=  "\
    abiword \
    qpdfview \
    "
#Tools    
IMAGE_INSTALL += "\
    speedcrunch \
    "    
#Graphics    
IMAGE_INSTALL +=  "\
    gimp "
