#Internet apps
IMAGE_INSTALL += "\
    firefox \
    qbittorrent \
    kvirc \
    "
#Multimedia apps
IMAGE_INSTALL += "\
    gstreamer1.0-plugins-base \
    gst-plugins-good \
    gst-plugins-bad \
    gst-plugins-ugly \
    mpv \
    audacious \
    audacious-plugins \
"
#Music tools
IMAGE_INSTALL += "\
    qjackctl \
    fluidsynth \
    qtractor \
    rosegarden \
    "

#Video edition
IMAGE_INSTALL += "\    
    shotcut \
    "

#Productivity
IMAGE_INSTALL +=  "\
    libreoffice \
    qpdfview \
    "
#Tools    
IMAGE_INSTALL += "\
    speedcrunch \
    "    
#Graphics    
IMAGE_INSTALL +=  "\
    gimp "
